apiVersion: core.clrslate.io
kind: ModelDefinition
metadata:
  name: helm.model.helmRelease
  title: Helm Release
  description: Helm Release
spec:
  schema:
    properties:
      name:
        type: string
        description: The name of the Helm release
      namespace:
        type: string
        description: The namespace of the Helm release
      createNamespace:
        type: boolean
        description: Whether to create the namespace for the Helm release
        default: false
      values:
        type: object
        description: Collection of key-value pairs to be used for the Helm chart installation
        additionalProperties:
          type: string
      valuesFile:
        type: string
        description: Values file template to be used for the Helm chart installation
    required:
      - name
      - namespace  
  mirrored:
    command:
      type: string
      value: |
        {%- assign versionFlag = chart.version | default: "" -%}
        {%- if versionFlag != "" -%}
          {%- assign versionFlag = " --version " | append: versionFlag -%}
        {%- endif -%}
        {%- assign createNsFlag = "" -%}
        {%- if createNamespace -%}
          {%- assign createNsFlag = " --create-namespace" -%}
        {%- endif -%}
        {%- assign valuesFileFlag = "" -%}
        {%- assign setValues = "" -%}
        {%- if values and values != empty -%}
          {%- assign setPairs = "" -%}
          {%- for key in values -%}
            {%- assign setPairs = setPairs | append: key | append: "=" | append: values[key] | append: "," -%}
          {%- endfor -%}
          {%- assign setValues = " --set " | append: setPairs -%}
        {%- endif -%}
        {%- capture command -%}helm upgrade --install {{name}} {{chart.name}} {{versionFlag}} --namespace {{namespace}} {{createNsFlag}} {{setValues}}{%- endcapture -%}
        {{- command | strip -}}
  relations:
    chart:
      title: Helm Chart
      description: The Helm chart to be used for the release
      format: resource
      required: true
      many: false
      specifications:
        type: helm.model.helmChart
