apiVersion: core.clrslate.io
kind: ModelDefinition
metadata:
  name: helm.model.helmRelease
  title: Helm Release
  description: Helm Release
spec:
  schema:
    properties:
      name:
        type: string
        title: Name
        description: The name of the Helm release
      namespace:
        type: string
        title: Namespace
        description: The namespace of the Helm release
      createNamespace:
        type: boolean
        title: Create Namespace
        description: Whether to create the namespace for the Helm release
        default: false
      values:
        type: object
        title: Values
        description: Collection of key-value pairs to be used for the Helm chart installation
      valuesFile:
        type: string
        title: Values File
        description: Values file template to be used for the Helm chart installation
      chart:
        type: object
        title: Helm Chart
        description: The Helm chart to be used for the release
        format: resource
        specifications:
          type: helm.model.helmChart
    required:
      - name
      - namespace  
  mirrored:
    command:
      type: string
      value: |
        {%- assign versionFlag = inputs.chart.version | default: "" -%}
        {%- if versionFlag != "" -%}
          {%- assign versionFlag = " --version " | append: versionFlag -%}
        {%- endif -%}
        {%- assign repoFlag = "" -%}
        {%- if inputs.chart.repository and inputs.chart.repository != "" -%}
          {%- assign repoFlag = " --repo " | append: inputs.chart.repository -%}
        {%- endif -%}
        {%- assign createNsFlag = "" -%}
        {%- if inputs.createNamespace -%}
          {%- assign createNsFlag = " --create-namespace" -%}
        {%- endif -%}
        {%- assign valuesFileFlag = "" -%}
        {%- assign setValues = "" -%}
        {%- if inputs.values and inputs.values != empty -%}
          {%- assign setPairs = "" -%}
          {%- for key in inputs.values -%}
            {%- assign setPairs = setPairs | append: key | append: "=" | append: inputs.values[key] | append: "," -%}
          {%- endfor -%}
          {%- assign setValues = " --set " | append: setPairs -%}
        {%- endif -%}
        {%- capture command -%}helm upgrade --install {{inputs.name}} {{inputs.chart.name}} {{inputs.versionFlag}}{{repoFlag}} --namespace {{inputs.namespace}} {{createNsFlag}} {{setValues}}{%- endcapture -%}
        {{- command | strip -}}
