apiVersion: tekton.clrslate.io
kind: PipelineRef
metadata:
  name: helm.pipelineRef.helm-install
  title: Helm Install
  description: An activity that installs Helm releases in the given clusters
  labels:
    category: Helm
    owner: clrslate
    package: k8s
  tags:
    - tekton
    - kubernetes
    - create
spec:
  schema:
    properties:
      cluster:
        type: object
        format: resource
        title: Target Cluster
        description: Target Kubernetes Cluster
        specifications:
          type: azure.model.aks
      helmChart:
        type: object
        format: resource
        title: Target Helm Chart
        description: Target Helm Chart
        specifications:
          type: helm.model.helmChart
      releaseName:
        type: string
        description: The name of the Helm release
      namespace:
        type: string
        description: The namespace of the Helm release
      createNamespace:
        type: boolean
        description: Whether to create the namespace for the Helm release
        default: false
      values:
        type: object
        description: Collection of key-value pairs to be used for the Helm chart installation
      valuesFile:
        type: string
        description: Values file template to be used for the Helm chart installation
    required:
      - cluster
      - helmChart
      - releaseName
      - namespace  
  mirrored:
    command:
      type: string
      value: |
        {%- assign versionFlag = chart.version | default: "" -%}
        {%- if versionFlag != "" -%}
          {%- assign versionFlag = " --version " | append: versionFlag -%}
        {%- endif -%}
        {%- assign repoFlag = "" -%}
        {%- if helmChart.repository and helmChart.repository != "" -%}
          {%- assign repoFlag = " --repo " | append: helmChart.repository -%}
        {%- endif -%}
        {%- assign createNsFlag = "" -%}
        {%- if createNamespace -%}
          {%- assign createNsFlag = " --create-namespace" -%}
        {%- endif -%}
        {%- assign setValues = "" -%}
        {%- if values and values != empty -%}
          {%- assign setPairs = "" -%}
          {%- for key in values -%}
            {%- assign setPairs = setPairs | append: key | append: "=" | append: values[key] | append: "," -%}
          {%- endfor -%}
          {%- assign setValues = " --set " | append: setPairs -%}
        {%- endif -%}
        {%- capture command -%}helm upgrade --install {{releaseName}} {{helmChart.name}} {{versionFlag}} {{repoFlag}} --namespace {{namespace}} {{createNsFlag}} {{setValues}}{%- endcapture -%}
        {{- command | strip -}}
  pipeline:
    pipelineRef: k8s.script.pipeline
    params:
      image: "{{inputs.cluster.image}}"
      script: |
        {{inputs.cluster.loginScript}}
        {{inputs.command}} --values manifests/values.yaml
    secretMounts:
      credentialsRef: "{{inputs.cluster.credentials._name}}"
    files:
      values.yaml: |
        {{inputs.helmChart.valuesFile}}
