apiVersion: tekton.clrslate.io
kind: PipelineRef
metadata:
  name: github.pipelineRef.gh-script
  title: GitHub script
  description: A pipeline reference that allows you to run a gh script to work with GitHub
  tags:
    - tekton
    - github
    - create
spec:
  schema:
    properties:
      credentials:
        type: object
        format: secret
        title: Personal Access Token
        description: GitHub personal access token for authentication
        specifications:
          type: github.secret.personalAccessToken
          mount: true
          mountParamName: secretRef
      script:
        type: string
        title: Target Script
        description: Target Script
    required:
      - credentials
      - script
  pipeline:
    pipelineRef: clrslate.github.pipelines.script
    params:
      script: '{{inputs.script}}'
