apiVersion: core.clrslate.io
kind: Activity
metadata:
  name: k8s.activity.create-namespaces
  title: Create k8s Namespace
  description: An activity that creates namespaces in the given clusters
  labels:
    category: Kubernetes
    owner: clrslate
    package: k8s
  tags:
    - tekton
    - kubernetes
    - create
spec:
  inputs:
    properties:
      cluster:
        type: object
        format: resource
        title: Target Cluster
        description: Target Kubernetes Cluster
        specifications:
          type: azure.model.aks
      namespace:
        type: string
        title: Namespace
        description: The name of the namespace to create
    required:
      - cluster
      - namespace
  mirrored:
    command:
      type: string
      value: |
        kubectl create namespace {{inputs.namespace}} --dry-run=client -o yaml | kubectl apply -f -
  handler:
    type: tekton.pipelineRef
    properties:
      pipeline: k8s.pipelineRef.kubectl-script
      inputs:
        script: '{{inputs.command}}'
        cluster: '{{inputs.cluster._name}}'
      resources:
        newNamespace:
          apiVersion: records.clrslate.io
          kind: k8s.model.namespace
          metadata:
            name: "k8s.model.namespace.{{inputs.namespace}}"
            title: "{{inputs.namespace}}"
            description: "Kubernetes namespace {{inputs.namespace}}"
            icon: Kubernetes.Logo
            labels:
              category: Kubernetes
            tags:
              - kubernetes
              - namespace
          spec:
            name: "{{inputs.namespace}}"
            cluster: "{{inputs.cluster._metadata.name}}"


  
