apiVersion: core.clrslate.io
kind: Activity
metadata:
  name: crossplane.azure.activity.configure-provider-config
  title: Configure Provider Config
  description: An activity to configure Crossplane provider config for Azure
  logo: Azure.Logo
  labels:
    category: Azure Crossplane
    executionType: DesiredState
  tags:
    - crossplane
    - azure
    - resourceGroup
    - apply
spec:
  inputs:
    properties:
      subscription:
        type: object
        format: resource        
        title: Azure Subscription
        description: The subscription to create the resource group in
        specifications:
          type: azure.model.subscription
  mirrored:
    providerDefinition:
      type: string
      title: Provider Definition
      description: The provider config definition template
      value: |
        apiVersion: azure.m.upbound.io/v1beta1
        kind: ProviderConfig
        metadata:
          name: {{ inputs.subscription._safeName  }}
          namespace: {{ global.Org.Identifier }}
        spec:
          credentials:
            source: Secret
            secretRef:
              namespace: {{ Global.Org.Identifier }}
              name: {{ inputs.subscription._safeName  }}-secret
              key: creds
    providerCredentialsJson:
      type: string
      title: Provider Credentials JSON
      description: The provider credentials in JSON format
      value: |
        {
          "subscriptionId": "{{ inputs.subscription.subscriptionId }}",
          "tenantId": "{{ inputs.subscription.tenantId }}",
          "clientId": "{{ inputs.subscription.clientId }}",
          "clientSecret": "{{ inputs.subscription.clientSecret }}"
          "activeDirectoryEndpointUrl": "{{ inputs.subscription.activeDirectoryEndpointUrl  }}",
          "resourceManagerEndpointUrl": "{{ inputs.subscription.resourceManagerEndpointUrl  }}",
          "activeDirectoryGraphResourceId": "{{ inputs.subscription.activeDirectoryGraphResourceId  }}",
          "sqlManagementEndpointUrl": "{{ inputs.subscription.sqlManagementEndpointUrl }}",
          "galleryEndpointUrl": "{{ inputs.subscription.galleryEndpointUrl  }}",
          "managementEndpointUrl": "{{ inputs.subscription.managementEndpointUrl }}"  
        }
  handler:
    type: tekton.pipelineRef
    properties:
      pipeline: k8s.pipelineRef.kubectl-apply-tenant
      inputs:
        serviceAccount: tekton-actions-account
        namespace: '{{ global.Org.Identifier }}'
        values: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: {{ inputs.subscription._safeName  }}-secret
            namespace: {{ global.Org.Identifier | kebabize }}
          type: Opaque
          data:
            creds: {{ inputs.providerCredentialsJson | base64 }}
          ---
          {{ inputs.providerDefinition }}
          