apiVersion: core.clrslate.io
kind: Activity
metadata:
  name: keycloak.role.createRole
  title: Create Role
  description: Create a new role in a Keycloak realm
  labels:
    category: Keycloak
  tags:
    - create
    - role
    - keycloak
spec:
  inputs:
    properties:
      realmName:
        type: string
        title: Realm Name
        description: Name of the realm to create the role in
      roleName:
        type: string
        title: Role Name
        description: Name of the role to create
      keycloakUrl:
        type: string
        title: Keycloak URL
        description: Base URL of the Keycloak server
      authToken:
        type: string
        title: Authentication Token
        description: Admin authentication token for Keycloak
    required:
      - realmName
      - roleName
      - keycloakUrl
      - authToken
  handler:
    type: console
    properties:
      output: |
        🛡️ Keycloak Role Creation
        =========================
        Realm Name: {{inputs.realmName}}
        Role Name: {{inputs.roleName}}
        Keycloak URL: {{inputs.keycloakUrl}}
        Auth Token: [PROTECTED]

        ✅ Role created successfully!
