apiVersion: core.clrslate.io
kind: Activity
metadata:
  name: keycloak.client.deleteClient
  title: Delete Client
  description: Delete a client from a Keycloak realm
  labels:
    category: Keycloak
  tags:
    - delete
    - client
    - keycloak
spec:
  inputs:
    properties:
      realmName:
        type: string
        title: Realm Name
        description: Name of the realm containing the client
      clientId:
        type: string
        title: Client ID
        description: ID of the client to delete
      keycloakUrl:
        type: string
        title: Keycloak URL
        description: Base URL of the Keycloak server
      authToken:
        type: string
        title: Authentication Token
        description: Admin authentication token for Keycloak
    required:
      - realmName
      - clientId
      - keycloakUrl
      - authToken
  handler:
    type: console
    properties:
      output: |
        🗑️ Keycloak Client Deletion
        ============================
        Realm Name: {{inputs.realmName}}
        Client ID: {{inputs.clientId}}
        Keycloak URL: {{inputs.keycloakUrl}}
        Auth Token: [PROTECTED]

        ✅ Client deleted successfully!
