apiVersion: core.clrslate.io
kind: Activity
metadata:
  name: github.activity.tekton.listRepositories
  title: Github List Repositories
  description: An activity that runs a Tekton pipeline to list GitHub repositories
  labels:
    category: GitHub
    owner: clrslate
    package: github
  tags:
    - tekton
    - github
    - list-repositories
spec:
  inputs:
    properties:
      githubToken:
        type: object
        format: secret
        title: GitHub Token
        description: Token to access GitHub resources
        specifications:
          type: github.secret.personalAccessToken
          mount: true
          mountParamName: secretRef
      organization:
        type: string
        title: GitHub Organization
        description: The GitHub organization to list repositories from
        default: clrslate
    required:
      - githubToken
      - organization
  handler:
    type: tekton
    properties:
      pipelineRef: clrslate.github.pipelines.script
      params:
        script: |
          echo "Fetching repositories for organization: {{inputs.organization}}"
          gh repo list {{inputs.organization}} --json name --limit 1000

