apiVersion: records.clrslate.io
kind: helm.model.helmChart
metadata:
  name: istio.records.helmChart.istiod
  title: Istiod
  description: Istiod helm chart
spec:
  name: istiod
  repository: https://istio-release.storage.googleapis.com/charts
  version: 1.21.1
  namespace: istio-system
  values: |
    meshConfig:
      accessLogFile: /dev/stdout
      defaultConfig:
        gatewayTopology:
          numTrustedProxies: '2'
    global:
      proxy:
        logLevel: info
