apiVersion: core.clrslate.io
kind: ModelDefinition
metadata:
  name: k8s.model.clusterProvider
  title: Kubernetes Cluster Provider
  description: A Kubernetes cluster provider
  icon: Cluster
  labels:
    owner: clrslate
    package: k8s
spec:
  schema:
    properties:
      loginScript:
        type: string
        description: The name of the Kubernetes cluster provider.
      providerType:
        type: string
        description: The type of the Kubernetes cluster provider (e.g., GKE, EKS, AKS).
    required:
      - name
      - providerType