apiVersion: core.clrslate.io
kind: ModelDefinition
metadata:
  name: k8s.model.namespace
  title: K8s Namespace
  description: A Kubernetes namespace
  labels:
    owner: clrslate
    package: k8s
spec:
  schema:
    properties:
      name:
        type: string
        description: The name of the namespace
      cluster:
        title: Cluster
        description: The Kubernetes cluster this Node belongs to
        format: resource
        required: false
        many: false
        specifications:
          type: k8s.cluster
    required:
      - name
