apiVersion: core.clrslate.io
kind: Activity
metadata:
  name: clrslatePlatform.activity.deployCore
  title: Deploy ClrSlate Core
  description: Deploy ClrSlate Core
  labels:
    category: ClrSlate Platform
  tags:
    - create
spec:
  inputs:
    properties:
      aksCluster:
        type: object
        format: resource
        title: AKS Cluster
        description: Azure Kubernetes Service Cluster
        specifications:
          type: azure.model.aks
      namespace:
        type: string
        description: The namespace of the Helm release (optional, defaults to chart namespace)
    required:
      - aksCluster
  resources:
    helmChart:
      type: RecordEntry
      value: clrslatePlatform.records.helmChart.clrCore
  handler:
    type: tekton.pipelineRef
    properties:
      pipeline: helm.pipelineRef.helm-install
      inputs:
        cluster: "{{inputs.aksCluster._name}}"
        helmChart: "{{inputs.helmChart._name}}"
        releaseName: clrcore
        namespace: "{{inputs.namespace}}"



  
