apiVersion: core.clrslate.io
kind: Activity
metadata:
  name: clrslatePlatform.activity.deployCore
  title: Deploy ClrSlate Core
  description: Deploy ClrSlate Core
  labels:
    category: ClrSlate Platform
  tags:
    - create
spec:
  inputs:
    properties:
      environment:
        type: object
        format: resource
        title: Environment
        description: Target Environment
        specifications:
          type: clrslatePlatform.model.clrslate-environment
      tenantName:
        type: string
        title: Tenant Name
        description: The name of the tenant to deploy Forge for
    required:
      - environment
      - tenantName
  mirrored:
    tenantNameSlug:
      type: string
      value: "{{inputs.tenantName | kebabize}}"
  resources:
    helmChart:
      type: RecordEntry
      value: clrslatePlatform.records.helmChart.clrCore
  handler:
    type: tekton.pipelineRef
    properties:
      pipeline: helm.pipelineRef.helm-install
      inputs:
        cluster: "{{inputs.environment.cluster._name}}"
        helmChart: "clrslatePlatform.records.helmChart.clrCore"
        releaseName: clrCore
        namespace: "{{inputs.tenantNameSlug}}"
        valuesFile: |
          ingress:
            enabled: true
            gateway: {{inputs.environment.gateway.name}}
            domain:
              base: {{inputs.environment.gateway.domain}}
              sub: {{inputs.tenantNameSlug}}-api
          image:
            pullPolicy: Always



  
