apiVersion: core.clrslate.io
kind: Activity
metadata:
  name: clrslatePlatform.security.createClientCredentialsSecret
  title: Create Client Credentials Secret
  description: Create a Kubernetes secret from client credentials using kubectl script.
  tags: [create, kubernetes, secret, client-credentials]
spec:
  inputs:
    properties:
      aksCluster:
        type: object
        format: resource
        title: AKS Cluster
        description: Azure Kubernetes Service Cluster
        specifications:
          type: azure.model.aks
      secretName:
        type: string
        description: Name for the Kubernetes secret
      namespace:
        type: string
        description: Target Kubernetes namespace
      credentials:
        type: object
        format: secret
        title: Client Credentials
        description: Secret containing clientId and clientSecret
        specifications:
          type: clrslatePlatform.secret.client-credentials
          mount: true
    required:
    - secretName
    - namespace
    - credentials
  handler:
    type: tekton.pipelineRef
    properties:
      pipeline: k8s.pipelineRef.kubectl-script
      inputs:
        script: |
          kubectl create secret generic {{inputs.secretName | kebabize }} \
            --from-literal=realm__clientId={{inputs.credentials.clientId}} \
            --from-literal=realm__clientSecret={{inputs.credentials.clientSecret}} \
            -n {{inputs.namespace}} --dry-run=client -o yaml | kubectl apply -f -
        cluster: '{{inputs.aksCluster._name}}'
