apiVersion: core.clrslate.io
kind: Activity
metadata:
  name: clrslatePlatform.activity.deployClrSlateMongo
  title: Deploy ClrSlate Mongo
  description: Deploy ClrSlate Mongo
  labels:
    category: ClrSlate Platform
  tags:
    - create
spec:
  inputs:
    properties:
      cluster:
        type: object
        format: resource
        title: Cluster
        description: Target Kubernetes Cluster
        specifications:
          type: azure.model.aks
      namespace:
        type: string
        description: The namespace of the Helm release
    required:
      - cluster
  handler:
    type: tekton.pipelineRef
    properties:
      pipeline: helm.pipelineRef.helm-install
      inputs: 
        cluster: "{{inputs.cluster._name}}"
        helmChart: "clrslatePlatform.records.helmChart.clrslate-mongo"
        releaseName: mongo
        namespace: "{{inputs.namespace}}"