apiVersion: core.clrslate.io
kind: Activity
metadata:
  name: clrslatePlatform.activity.deployForge
  title: Deploy Forge
  description: Deploy Forge
  labels:
    category: ClrSlate Platform
  tags:
    - create
spec:
  inputs:
    properties:
      aksCluster:
        type: object
        format: resource
        title: AKS Cluster
        description: Azure Kubernetes Service Cluster
        specifications:
          type: azure.model.aks
    required:
      - aksCluster
  resources:
    helmChart:
      type: RecordEntry
      value: clrslatePlatform.records.helmChart.clrslateAppMinimal
  handler:
    type: console
    properties:
      output: |
        {{inputs.helmChart.name}}.{{inputs.helmChart.version}}


  
