apiVersion: core.clrslate.io
kind: Activity
metadata:
  name: clrslatePlatform.activity.deployForge
  title: Deploy Forge
  description: Deploy Forge
  labels:
    category: ClrSlate Platform
  tags:
    - create
spec:
  inputs:
    properties:
      environment:
        type: object
        format: resource
        title: Environment
        description: Target Environment
        specifications:
          type: clrslatePlatform.model.clrslate-environment
      tenantName:
        type: string
        title: Tenant Name
        description: The name of the tenant to deploy Forge for
    required:
      - environment
      - tenantName
  mirrored:
    tenantNameSlug:
      type: string
      value: "{{inputs.tenantName | kebabize}}"
  handler:
    type: tekton.pipelineRef
    properties:
      pipeline: helm.pipelineRef.helm-install
      inputs:
        cluster: "{{inputs.environment.cluster._name}}"
        helmChart: "clrslatePlatform.records.helmChart.clrforge"
        releaseName: clrforge
        namespace: "{{inputs.tenantNameSlug}}"
        valuesFile: |
          ingress:
            enabled: true
            gateway: {{inputs.environment.gateway.name}}
            domain:
              base: {{inputs.environment.gateway.domain}}
              sub: {{inputs.tenantNameSlug}}
          image:
            pullPolicy: Always
      resources:
        newTenant:
          apiVersion: records.clrslate.io
          kind: clrslatePlatform.model.clrslate-tenant
          metadata:
            name: "clrslate.model.tenant.{{inputs.tenantNameSlug}}"
            title: "{{inputs.tenantName}}"
            description: "ClrSlate tenant: {{inputs.tenantName}}"
            icon: Brands.ClrSlate
            labels:
              category: Tenant
            tags:
              - kubernetes
              - namespace
              - istio
          spec:
            name: "{{inputs.tenantName}}"
            domain: "{{inputs.tenantNameSlug}}.{{inputs.environment.gateway.domain}}"
            environment: "{{inputs.environment._name}}"



  
