apiVersion: core.clrslate.io
kind: WorkflowStack
metadata:
  isSelfServiceAction: true
  folderPath: Teams/Admin
  name: workstreamB
  title: "Startup: Workstream B: Developer Tools & Environment"
  description: Provision accounts Azure DevOps, IDE Setup- Visual Studio Professional
  icon: Azure.DevOps
  tags:
    - Devops
  labels: {}
  annotations: {}
spec:
  variables:
    - id: f86504fc59ff1bf3
      name: project
      typeName: String
      isArray: false
      storageDriverTypeName: Elsa.Workflows.WorkflowInstanceStorageDriver, Elsa.Workflows.Core
  inputs:
    - uIHint: singleline
      storageDriverType: Elsa.Workflows.WorkflowInstanceStorageDriver, Elsa.Workflows.Core
      type: String
      isArray: false
      name: Email
      displayName: Email
      description: ""
      category: ""
  outputs:
    - type: String
      isArray: false
      name: DevopsAccess
      displayName: Devops Access
      description: ""
      category: Primitives
    - type: String
      isArray: false
      name: VisualStudioProfessionalAccess
      displayName: Visual Studio Professional Access
      description: ""
      category: Primitives
  customProperties:
    icon: Azure.DevOps
    color:
    tags:
      - Devops
    isSelfServiceAction: true
    folderPath: Teams/Admin
  options:
    usableAsActivity: true
    autoUpdateConsumingWorkflows: true
  root:
    id: fc8d25d13be46a02
    nodeId: Workflow1:fc8d25d13be46a02
    name: Flowchart1
    type: Elsa.Flowchart
    version: 1
    customProperties:
      notFoundConnections: []
      canStartWorkflow: false
      runAsynchronously: false
    metadata: {}
    activities:
      - id: d304dc0294259476
        nodeId: Workflow1:fc8d25d13be46a02:d304dc0294259476
        name: Start1
        type: Elsa.Start
        version: 1
        customProperties:
          canStartWorkflow: false
          runAsynchronously: false
        metadata:
          designer:
            position:
              x: -432.48785400390625
              y: -78.97917556762695
            size:
              width: 101.3125
              height: 49.333335876464844
            displayText: Start
      - variable:
          id: f86504fc59ff1bf3
          name: project
          typeName: String
          storageDriverTypeName: Elsa.Workflows.WorkflowInstanceStorageDriver, Elsa.Workflows.Core
        value:
          typeName: Object
          expression:
            type: Literal
            value: MVP_v1.0
        id: b0d347c8040e5f66
        nodeId: Workflow1:fc8d25d13be46a02:b0d347c8040e5f66
        name: SetVariable1
        type: Elsa.SetVariable
        version: 1
        customProperties:
          canStartWorkflow: false
          runAsynchronously: false
        metadata:
          designer:
            position:
              x: -180
              y: -148.07640075683594
            size:
              width: 152.3229217529297
              height: 49.333335876464844
            displayText: Set Variable
      - result: null
        id: c47da25b85c87f00
        nodeId: Workflow1:fc8d25d13be46a02:c47da25b85c87f00
        name: visualstudio.professional.giveaccess1
        type: visualstudio.professional.giveaccess
        version: 1
        customProperties:
          canStartWorkflow: false
          runAsynchronously: false
        metadata:
          designer:
            position:
              x: -180
              y: 0
            size:
              width: 248.5416717529297
              height: 49.333335876464844
            displayText: Visual Studio Professional Access
        inputEmail:
          typeName: String
          expression:
            type: Input
            value: Email
          memoryReference:
            id: c47da25b85c87f00:input-input-email
      - result: null
        id: 17a74005dbcdf63e
        nodeId: Workflow1:fc8d25d13be46a02:17a74005dbcdf63e
        name: azure.devops.giveaccess1
        type: azure.devops.giveaccess
        version: 1
        customProperties:
          canStartWorkflow: false
          runAsynchronously: false
        metadata:
          designer:
            position:
              x: 39.51214599609375
              y: -148.07640075683594
            size:
              width: 177.4166717529297
              height: 49.333335876464844
            displayText: Azure DevOps Access
        inputEmail:
          typeName: String
          expression:
            type: Input
            value: Email
          memoryReference:
            id: 17a74005dbcdf63e:input-input-email
        inputProjectList:
          typeName: String
          expression:
            type: Variable
            value:
              id: f86504fc59ff1bf3
              name: project
              typeName: String
              storageDriverTypeName: Elsa.Workflows.WorkflowInstanceStorageDriver, Elsa.Workflows.Core
          memoryReference:
            id: 17a74005dbcdf63e:input-input-project-list
      - outputName:
          typeName: String
          expression:
            type: Literal
            value: VisualStudioProfessionalAccess
        outputValue:
          typeName: Object
          expression:
            type: Literal
            value: Visual Studio Professional Access successfully provided
        id: bd1f1e8108972c9e
        nodeId: Workflow1:fc8d25d13be46a02:bd1f1e8108972c9e
        name: SetOutput2
        type: Elsa.SetOutput
        version: 1
        customProperties:
          canStartWorkflow: false
          runAsynchronously: false
        metadata:
          designer:
            position:
              x: 137.08853149414062
              y: 0
            size:
              width: 106.98958587646484
              height: 49.333335876464844
            displayText: Set Output
      - outputName:
          typeName: String
          expression:
            type: Literal
            value: DevopsAccess
        outputValue:
          typeName: Object
          expression:
            type: Liquid
            value: "Devops Access successfully granted for project: {{Variables.project}}"
        id: 2b45431ab97d938
        nodeId: Workflow1:fc8d25d13be46a02:2b45431ab97d938
        name: SetOutput1
        type: Elsa.SetOutput
        version: 1
        customProperties:
          canStartWorkflow: false
          runAsynchronously: false
        metadata:
          designer:
            position:
              x: 283.51214599609375
              y: -148.07640075683594
            size:
              width: 106.98958587646484
              height: 49.333335876464844
            displayText: Set Output
    variables: []
    connections:
      - source:
          activity: c47da25b85c87f00
          port: Done
        target:
          activity: bd1f1e8108972c9e
          port: In
        vertices: []
      - source:
          activity: b0d347c8040e5f66
          port: Done
        target:
          activity: 17a74005dbcdf63e
          port: In
        vertices: []
      - source:
          activity: 17a74005dbcdf63e
          port: Done
        target:
          activity: 2b45431ab97d938
          port: In
        vertices: []
      - source:
          activity: d304dc0294259476
          port: Done
        target:
          activity: c47da25b85c87f00
          port: In
        vertices: []
      - source:
          activity: d304dc0294259476
          port: Done
        target:
          activity: b0d347c8040e5f66
          port: In
        vertices: []
