apiVersion: records.clrslate.io
kind: observability.model.grafanaConfig
metadata:
  name: observability.records.config.grafana-dev
  title: Grafana Development Configuration
  description: Development environment configuration for Grafana
  labels:
    category: Observability
    package: observability
    environment: dev
    component: visualization
  tags:
    - grafana
    - development
    - visualization
spec:
  environment: dev
  persistence:
    enabled: false
    size: "1Gi"
    storageClass: ""
  admin:
    user: "admin"
    password: "admin123"
  datasources:
    prometheus:
      enabled: true
      url: "http://prometheus-stack-kube-prom-prometheus:9090"
    loki:
      enabled: true
      url: "http://loki:3100"
  dashboards:
    kubernetes: true
    prometheus: true
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"