apiVersion: records.clrslate.io
kind: observability.model.lokiConfig
metadata:
  name: observability.records.config.loki-prod
  title: Loki Production Configuration
  description: Production environment configuration for Loki
  labels:
    category: Observability
    package: observability
    environment: prod
    component: logging
  tags:
    - loki
    - production
    - logging
spec:
  environment: prod
  deploymentMode: "SimpleScalable"
  storage:
    type: "filesystem"
    retention: "720h"
    size: "100Gi"
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  replication:
    factor: 3
  limits:
    ingestionRate: "8M"
    queryTimeout: "2m"