
apiVersion: core.clrslate.io
kind: Activity
metadata:
  name: istio.activity.deployIstioIstioGateway
  title: Deploy Istio IstioGateway
  description: Deploy Istio IstioGateway Helm Chart
  labels:
    category: Istio
  tags:
    - create
spec:
  inputs:
    properties:
      cluster:
        type: object
        format: resource
        title: Cluster
        description: Target Kubernetes Cluster
        specifications:
          type: azure.model.aks
    required:
      - cluster
  handler:
    type: tekton.pipelineRef
    properties:
      pipeline: helm.pipelineRef.helm-install
      inputs: 
        cluster: "{{inputs.cluster._name}}"
        helmChart: "istio.records.helmChart.istio-istioGateway"
        releaseName: istio-istioGateway
        namespace: "{{inputs.namespace}}"
