apiVersion: core.clrslate.io
kind: ModelDefinition
metadata:
  name: clrslatePlatform.model.clrslate-tenant
  title: ClrSlate Tenant
  description: Represents a tenant with a name, environment reference, and a slug computed from the name.
spec:
  schema:
    required:
      - name
      - environment
    properties:
      name:
        title: Tenant Name
        type: string
        description: Tenant Name
      domain:
        title: Domain
        type: string
        description: Domain for the tenant, used for routing and access
      environment:
        title: Environment
        type: object
        format: resource
        description: Reference to the ClrSlateEnvironment for this tenant
        specifications:
          type: clrslatePlatform.model.clrslate-environment
  mirrored:
    slug:
      type: string
      title: Slug
      description: Slug for the tenant, computed from the name
      pattern: '^[a-z0-9-]+$'
      min_length: 3
      max_length: 50
      value: "{{inputs.name | downcase | replace: ' ', '-' }}"
    cluster:
      type: object
      format: resource
      title: Cluster
      description: Reference to the AKS cluster for this tenant
      value: "{{inputs.environment.cluster._name}}"
      specifications:
        type: azure.model.aks
