apiVersion: core.clrslate.io
kind: Activity
metadata:
  name: azure.tekton.pipelinerun.create-resource-group
  title: Create Resource Group
  description: An activity that runs a Tekton pipeline to create a new Azure resource group
  labels:
    category: Azure
  tags:
    - azure
    - resourceGroup
    - create
spec:
  inputs:
    properties:
      subscription:
        type: object
        format: resource        
        title: Azure Subscription
        description: The subscription to create the resource group in
        specifications:
          type: azure.model.subscription
      name:
        type: string
        title: Resource Group name
        description: Name of the resource group to create
      location:
        type: string
        format: lookup
        title: Location           
        description: The location of the resource group
        default: centralindia
        specifications:
          type: azure.lookups.locations
    required:
      - azCredentials
  mirrored:
    command:
      type: string
      value: |
        echo "Creating Azure resource group {{inputs.name}} in {{inputs.location}}"
        az group create --name {{inputs.name}} --location {{inputs.location}}
  handler:
    type: tekton.pipelineRef
    properties:
      pipeline: azure.pipelineRef.azure-script
      inputs:
        credentials: '{{inputs.subscription.credentials._name}}'
        script: '{{inputs.command}}'
      resources:
        newResourceGroup:
          apiVersion: records.clrslate.io
          kind: azure.model.resourceGroup
          metadata:
            name: "azure.model.resourceGroup.{{inputs.name}}"
            title: "{{inputs.name}}"
            description: "Azure resource group {{inputs.name}}"
            icon: Azure.Logo
            labels:
              category: Azure
            tags:
              - azure
              - resourceGroup
          spec:
            name: "{{inputs.name}}"
            location: "{{inputs.location}}"
            subscription: "{{inputs.subscription._metadata.name}}"