apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: create-namespace-
spec:
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/clrslate/catalog.git
    - name: revision
      value: main
    - name: pathInRepo
      value: packages/kubernetes/pipelines/k8s-kubectl-script.yaml
  taskRunTemplate:
    serviceAccountName: kubernetes-actions-account
  params:
    - name: script
      value: |
        kubectl get namespace


