apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: k8s-kubectl-script
spec:
  params:
    - name: script
      description: The Kubernetes CLI script to run
      type: string
      default: "kubectl $@"
  tasks:
  - name: get-namespaces
    description: "get all namespaces in the cluster"
    taskRef:
      name: kubernetes-actions
    params:
    - name: script
      value: $(params.script)