apiVersion: core.clrslate.io
kind: Activity
metadata:
  name: sonarqube.scan.checkStatus
  title: Check Scan Status
  description: Check the status of an ongoing SonarQube scan
  labels:
    category: SonarQube
  tags:
    - scan
    - status
    - check
    - sonarqube
spec:
  inputs:
    properties:
      projectKey:
        type: string
        title: Project Key
        description: Unique key of the SonarQube project
      sonarHostUrl:
        type: string
        title: SonarQube Host URL
        description: SonarQube server URL
      authToken:
        type: string
        title: Authentication Token
        description: Authentication token for the SonarQube server
    required:
      - projectKey
      - sonarHostUrl
      - authToken
  handler:
    type: console
    properties:
      output: |
        📊 SonarQube Scan Status Check
        ==============================
        Project Key: {{inputs.projectKey}}
        SonarQube URL: {{inputs.sonarHostUrl}}
        Auth Token: [PROTECTED]

        ✅ Scan status retrieved successfully!
