apiVersion: core.clrslate.io
kind: Activity
metadata:
  name: sonarqube.qualityGate.checkQualityGate
  title: Check Quality Gate
  description: Verify if the SonarQube project passes the quality gate
  labels:
    category: SonarQube
  tags:
    - quality-gate
    - check
    - validation
    - sonarqube
spec:
  inputs:
    properties:
      projectKey:
        type: string
        title: Project Key
        description: Unique key of the SonarQube project
      sonarHostUrl:
        type: string
        title: SonarQube Host URL
        description: SonarQube server URL
      authToken:
        type: string
        title: Authentication Token
        description: Authentication token for the SonarQube server
    required:
      - projectKey
      - sonarHostUrl
      - authToken
  handler:
    type: console
    properties:
      output: |
        🚪 SonarQube Quality Gate Check
        ===============================
        Project Key: {{inputs.projectKey}}
        SonarQube URL: {{inputs.sonarHostUrl}}
        Auth Token: [PROTECTED]

        ✅ Quality gate status checked successfully!
