apiVersion: core.clrslate.io
kind: Activity
metadata:
  name: sonarqube.project.deleteProject
  title: Delete SonarQube Project
  description: Delete a project from SonarQube
  labels:
    category: SonarQube
  tags:
    - delete
    - project
    - cleanup
    - sonarqube
spec:
  inputs:
    properties:
      projectKey:
        type: string
        title: Project Key
        description: Unique key of the SonarQube project to delete
      sonarHostUrl:
        type: string
        title: SonarQube Host URL
        description: SonarQube server URL
      authToken:
        type: string
        title: Authentication Token
        description: Authentication token for the SonarQube server
    required:
      - projectKey
      - sonarHostUrl
      - authToken
  handler:
    type: console
    properties:
      output: |
        🗑️ SonarQube Project Deletion
        ==============================
        Project Key: {{inputs.projectKey}}
        SonarQube URL: {{inputs.sonarHostUrl}}
        Auth Token: [PROTECTED]

        ✅ Project deleted successfully!
