apiVersion: core.clrslate.io
kind: Activity
metadata:
  name: redis.operations.pop
  title: Pop
  description: Pop data from a Redis list
  labels:
    category: Redis
  tags:
    - pop
    - list
    - data
    - redis
spec:
  inputs:
    properties:
      list:
        type: string
        title: List
        description: Name of the list in Redis
      tail:
        type: string
        title: Tail
        description: Whether to pop data from the end of the list
        enum: ["true", "false"]
        default: "false"
      propertyName:
        type: string
        title: Property Name
        description: Optional name of the property to write received data to
        default: ""
      dotNotation:
        type: string
        title: Dot Notation
        description: Whether to use dot-notation in property names
        enum: ["true", "false"]
        default: "true"
    required:
      - list
  handler:
    type: console
    properties:
      output: |
        ⬇️ Redis List Pop
        =================
        List: {{inputs.list}}
        Tail: {{inputs.tail}}
        Property Name: {{inputs.propertyName}}
        Dot Notation: {{inputs.dotNotation}}

        ✅ Data popped successfully!
