apiVersion: core.clrslate.io
kind: Activity
metadata:
  name: mongodb.activity.deployMongo
  title: Deploy MongoDB
  description: Deploy MongoDB Helm Chart
  tags:
    - create
    - helm
    - deploy
spec:
  inputs:
    properties:
      cluster:
        type: object
        format: resource
        title: Cluster
        description: Target Kubernetes Cluster
        specifications:
          type: azure.model.aks
      namespace:
        type: string
        description: The namespace of the Helm release
    required:
      - cluster
  handler:
    type: tekton.pipelineRef
    properties:
      pipeline: helm.pipelineRef.helm-install
      inputs:
        cluster: "{{inputs.cluster._name}}"
        helmChart: "mongodb.records.helmChart.mongodb"
        releaseName: mongo
        namespace: "{{inputs.namespace}}"
