apiVersion: records.clrslate.io
kind: helm.model.helmChart
metadata:
  name: observability.records.helmChart.loki
  title: Loki
  description: Loki log aggregation helm chart
  labels:
    category: Observability
    package: observability
    component: logging
  tags:
    - logging
    - loki
    - helm
spec:
  name: loki
  repository: https://grafana.github.io/helm-charts
  version: 6.3.4
  namespace: monitoring
  values: |
    # Default values for Loki
    # Basic configuration - use config records for environment-specific overrides
    deploymentMode: SingleBinary
    
    loki:
      commonConfig:
        replication_factor: 1
        path_prefix: /var/loki
      storage:
        type: 'filesystem'
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
      schemaConfig:
        configs:
          - from: 2024-04-01
            object_store: filesystem
            store: tsdb
            schema: v13
            index:
              prefix: index_
              period: 24h
      auth_enabled: false
      server:
        http_listen_port: 3100
        grpc_listen_port: 9095
      limits_config:
        ingestion_rate_mb: 4
        ingestion_burst_size_mb: 6
        per_stream_rate_limit: "3MB"
        per_stream_rate_limit_burst: "15MB"
        retention_period: 168h
      compactor:
        working_directory: /var/loki/compactor
        compaction_interval: 10m
        retention_enabled: true
        delete_request_store: filesystem
    
    # Single binary deployment for development
    singleBinary:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
      persistence:
        enabled: false
        size: 10Gi
      extraVolumes:
        - name: loki-data
          emptyDir: {}
        - name: loki-rules
          emptyDir: {}
        - name: loki-compactor
          emptyDir: {}
      extraVolumeMounts:
        - name: loki-data
          mountPath: /var/loki
        - name: loki-rules
          mountPath: /var/loki/rules
        - name: loki-compactor
          mountPath: /var/loki/compactor
    
    # Disable other components for single binary mode
    write:
      replicas: 0
    read:
      replicas: 0
    backend:
      replicas: 0
    
    # Monitoring configuration
    monitoring:
      serviceMonitor:
        enabled: true
        labels: {}
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
    
    # Test configuration
    test:
      enabled: false