apiVersion: core.clrslate.io
kind: ModelDefinition
metadata:
  name: observability.model.lokiConfig
  title: Loki Configuration
  description: Configuration model for Loki deployment settings
  labels:
    category: Observability
    package: observability
spec:
  schema:
    properties:
      environment:
        type: string
        title: Environment Type
        description: Deployment environment (dev or prod)
        enum: ["dev", "prod"]
        default: dev
      deploymentMode:
        type: string
        title: Deployment Mode
        description: Loki deployment architecture
        enum: ["SingleBinary", "SimpleScalable", "Distributed"]
        default: "SingleBinary"
      storage:
        type: object
        title: Storage Configuration
        description: Log storage settings
        properties:
          type:
            type: string
            title: Storage Type
            description: Backend storage type
            enum: ["filesystem", "s3", "gcs", "azure"]
            default: "filesystem"
          retention:
            type: string
            title: Log Retention Period
            description: How long to retain log data
            default: "168h"
          size:
            type: string
            title: Storage Size
            description: Size of persistent volume (filesystem only)
            default: "10Gi"
      resources:
        type: object
        title: Resource Limits
        description: CPU and memory resource configuration
        properties:
          requests:
            type: object
            properties:
              cpu:
                type: string
                default: "100m"
              memory:
                type: string
                default: "256Mi"
          limits:
            type: object
            properties:
              cpu:
                type: string
                default: "500m"
              memory:
                type: string
                default: "512Mi"
      replication:
        type: object
        title: Replication Settings
        description: Data replication configuration
        properties:
          factor:
            type: integer
            title: Replication Factor
            description: Number of replicas for data
            default: 1
            minimum: 1
            maximum: 3
      limits:
        type: object
        title: Rate Limits
        description: Ingestion and query rate limits
        properties:
          ingestionRate:
            type: string
            title: Ingestion Rate Limit
            description: Maximum ingestion rate per user
            default: "4M"
          queryTimeout:
            type: string
            title: Query Timeout
            description: Maximum query execution time
            default: "1m"
    required:
      - environment
      - deploymentMode