apiVersion: core.clrslate.io
kind: ModelDefinition
metadata:
  name: azure.model.aks
  title: Azure Kubernetes Service Cluster
  description: Represents an Azure Kubernetes Service (AKS) cluster
  labels:
    owner: clrslate
    package: azure
spec:
  schema:
    properties:
      name:
        type: string
        description: The name of the AKS cluster
      resourceGroup:
        type: object
        title: Azure Resource Group
        description: The Azure Resource Group associated with this Key Vault.
        format: resource
        required: true
        specifications:
          type: azure.model.resourceGroup
    required:
      - name
  mirrored:
    credentials:
      type: object
      format: secret
      description: Azure credentials associated with the AKS cluster
      value: '{{inputs.resourceGroup.subscription.credentials._name}}'
      specifications:
        type: azure.secret.clientCredentials
    loginScript:
      title: AKS Login Script
      description: Script template to be used by Tekton pipeline for azure login
      type: string
      format: script
      value: |
        az config set core.only_show_errors=true --only-show-errors
        az login --service-principal -u $clientId -p $clientSecret --tenant $tenantId -o none
        az account set --subscription $subscriptionId -o none
        az aks get-credentials --name {{inputs.name}} --resource-group {{inputs.resourceGroup.name}} -o none
    image:
      title: Image
      description: Container image to use for the AKS cluster
      type: string
      value: clrslatepublic.azurecr.io/tools/azure:latest
    pipelineRef:
      type: string
      title: Tekton Pipeline
      description: Reference to the Tekton pipeline for AKS deployment
      value: azure.pipelines.aks-script


