apiVersion: core.clrslate.io
kind: ModelDefinition
metadata:
  name: azure.model.containerRegistry
  title: Azure Container Registry
  description: Represents an Azure Container Registry (ACR)
  labels:
    owner: clrslate
    package: azure
spec:
  schema:
    properties:
      name:
        type: string
        description: The name of the Container Registry.
      loginServer:
        type: string
        description: The login server URL for the registry.
      sku:
        type: string
        description: The SKU (pricing tier) of the registry.
      adminUserEnabled:
        type: boolean
        description: Whether the admin user is enabled.
      registryPath:
        type: string
        description: The login server / path for the container registry (e.g., myregistry.azurecr.io)
    required:
      - name
      - loginServer
      - sku
  relations:
    resourceGroup:
      title: Azure Resource Group
      description: The Azure Resource Group associated with this Key Vault.
      format: resource
      required: true
      specifications:
        type: azure.model.resourceGroup
