apiVersion: core.clrslate.io
kind: SecretDefinition
metadata:
  name: azure.secret.clientCredentials
  title: Azure Credentials
  description: Azure service principal credentials
  labels:
    owner: clrslate
    package: azure
spec:
  schema:
    properties:
      clientId:
        type: string
        title: Client ID
        description: The client ID of the Azure Service Principal
      clientSecret:
        type: string
        title: Client Secret
        description: The client secret of the Azure Service Principal
      tenantId:
        type: string
        title: Tenant ID
        description: The tenant ID of the Azure Service Principal
      subscriptionId:
        type: string
        title: Subscription ID
        description: The subscription ID of the Azure Service Principal
    required:
      - clientId
      - clientSecret
      - subscriptionId
      - tenantId
