apiVersion: core.clrslate.io
kind: SecretDefinition
metadata:
  name: azure.secret.clientCredentials
  title: Azure Credentials
  description: Azure service principal credentials
  labels:
    owner: clrslate
    package: azure
spec:
  schema:
    properties:
      clientId:
        type: string
        title: Client ID
        description: The client ID of the Azure Service Principal
      clientSecret:
        type: string
        title: Client Secret
        description: The client secret of the Azure Service Principal
      tenantId:
        type: string
        title: Tenant ID
        description: The tenant ID of the Azure Service Principal
      subscriptionId:
        type: string
        title: Subscription ID
        description: The subscription ID of the Azure Service Principal
      activeDirectoryEndpointUrl:
        type: string
        title: Active Directory Endpoint URL
        description: The Active Directory endpoint URL for the Azure Service Principal
        default: https://login.microsoftonline.com
      resourceManagerEndpointUrl:
        type: string
        title: Resource Manager Endpoint URL
        description: The Azure Resource Manager endpoint URL
        default: https://management.azure.com/
      activeDirectoryGraphResourceId:
        type: string
        title: Active Directory Graph Resource ID
        description: The Active Directory Graph resource ID
        default: https://graph.windows.net/
      sqlManagementEndpointUrl:
        type: string
        title: SQL Management Endpoint URL
        description: The SQL Management endpoint URL
        default: https://management.core.windows.net:8443/
      galleryEndpointUrl:
        type: string
        title: Gallery Endpoint URL
        description: The Azure Gallery endpoint URL
        default: https://gallery.azure.com/
      managementEndpointUrl:
        type: string
        title: Management Endpoint URL
        description: The Azure Management endpoint URL
        default: https://management.core.windows.net/
    required:
      - clientId
      - clientSecret
      - subscriptionId
      - tenantId
