apiVersion: core.clrslate.io
kind: InvocationHandler
metadata:
  name: azure.invocation-handler.az-script
  title: Azure script Invocation Handler
  description: Azure script Invocation Handler
  labels:
    category: Azure
    owner: clrslate
    package: azure
  tags:
    - azure
    - invocation-handler
spec:
  inputs:
    properties:
    - name: credentials
      type: object
      format: secret
      title: Azure Credentials
      description: The Azure credentials to use for authentication
      specifications:
        type: azure.model.credentials
        mount: true  
        mountParamName: credentialsRef
    - name: script
      type: string
      description: The script to run in the pipeline
  handler:
    type: tekton
    properties:
      pipelineRef: azure.pipelines.azure-script
      params:
        script: "{{inputs.script}}"