apiVersion: records.clrslate.io
kind: helm.model.helmChart
metadata:
  name: metricsServer.records.helmChart.metrics-server
  title: Kubernetes Metrics Server (Bitnami)
  description: Bitnami Metrics Server Helm chart for Kubernetes cluster resource metrics aggregation
spec:
  name: metrics-server
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 7.4.5
  namespace: kube-system
  values: |
    # OpenShift compatibility
    global:
      compatibility:
        openshift:
          adaptSecurityContext: auto

    # Service Account security
    serviceAccount:
      automountServiceAccountToken: false

    # API Service configuration - disable to use existing
    apiService:
      create: false
      insecureSkipTLSVerify: true

    # Essential metrics-server arguments for production
    extraArgs:
      - --cert-dir=/tmp
      - --secure-port=8443
      - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
      - --kubelet-use-node-status-port
      - --metric-resolution=15s

    # Pod Disruption Budget for high availability
    pdb:
      create: true

    # System-critical scheduling priority
    priorityClassName: "system-cluster-critical"
    
    # Soft anti-affinity for better distribution
    podAntiAffinityPreset: soft

    # Optimized resource allocation
    resourcesPreset: "nano"

    # Network policies for security
    networkPolicy:
      enabled: true